name: picha_yangu_mobile
description: Flutter mobile app skeleton for Picha Yangu
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7
  intl: ^0.18.0
  dio: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
